# Movement tuning
MAX_POWER = 40
MIN_POWER = 25
SLOWDOWN_DISTANCE = 200
KP_HEADING = 1.2

# Gyro
GYRO_SETTLE_TIME = 0.2
MAX_CORRECTION = 30
CORRECTION_FACTOR = 1.2

# Color thresholds
RED_R_MIN = 230
RED_G_RATIO = 6
RED_B_RATIO = 7

GREEN_G_MIN = 200
GREEN_R_RATIO = 2
GREEN_B_RATIO = 2

ORANGE_R_MIN = 200
ORANGE_G_MIN = 100
ORANGE_B_RATIO_R = 3
ORANGE_B_RATIO_G = 2